//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpdtInject.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DpdtInject.Tests.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren0
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren0Module : DpdtModule
        ///    {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren0Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren0Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren1
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren1Module : DpdtModule
        ///    {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren1Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren1Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren2
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren2Module : DpdtModule
        ///    {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren2Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren3
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren3M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren3Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots0
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots0Module  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots0Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots0Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots1
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots1Module  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots1Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots1Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots2
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots2Module  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots2Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots3
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots3Module  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots3Module {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.Two.DifferentObjectDifferentCluster1
        ///{
        ///    public partial class ClusterTwoDifferentObjectDifferentCluster1Module : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterTwoDifferentObjectDifferentCluster1Module {
            get {
                return ResourceManager.GetString("ClusterTwoDifferentObjectDifferentCluster1Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy2
        ///{
        ///    public partial class ConditionalHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy2Module {
            get {
                return ResourceManager.GetString("ConditionalHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy3First
        ///{
        ///    public partial class ConditionalHierarchy3FirstModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public overr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy3FirstModule {
            get {
                return ResourceManager.GetString("ConditionalHierarchy3FirstModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy3Second
        ///{
        ///    public partial class ConditionalHierarchy3SecondModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy3SecondModule {
            get {
                return ResourceManager.GetString("ConditionalHierarchy3SecondModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.RContext.Hierarchy2
        ///{
        ///    public partial class ConditionalRContextHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalRContextHierarchy2Module {
            get {
                return ResourceManager.GetString("ConditionalRContextHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.RContext.Hierarchy2Variant1
        ///{
        ///    public partial class ConditionalRContextHierarchy2Variant1Module : DpdtModule
        ///    {
        ///        public const string BMessage = &quot;B some message [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalRContextHierarchy2Variant1Module {
            get {
                return ResourceManager.GetString("ConditionalRContextHierarchy2Variant1Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.RContext.Hierarchy2Variant2
        ///{
        ///    public partial class ConditionalRContextHierarchy2Variant2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalRContextHierarchy2Variant2Module {
            get {
                return ResourceManager.GetString("ConditionalRContextHierarchy2Variant2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.SingleObject
        ///{
        ///    public partial class ConditionalSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA1&gt;()
        ///                . [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalSingleObjectModule {
            get {
                return ResourceManager.GetString("ConditionalSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Constant.Hierarchy2WithSame
        ///{
        ///    public partial class ConstantHierarchy2WithSameModule : DpdtModule
        ///    {
        ///        public static A ConstantA1 = new A();
        ///        public static A ConstantA2 = new A();
        ///
        ///        public overri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstantHierarchy2WithSameModule {
            get {
                return ResourceManager.GetString("ConstantHierarchy2WithSameModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Constant.SingleObject
        ///{
        ///    public partial class ConstantSingleObjectModule : DpdtModule
        ///    {
        ///        public static A ConstantA = new A();
        ///
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConstantSingleObjectModule {
            get {
                return ResourceManager.GetString("ConstantSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Func.Generic.Singleton.Hierarchy2
        ///{
        ///    public partial class FuncGenericSingletonHierarchy2Module : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncGenericSingletonHierarchy2Module {
            get {
                return ResourceManager.GetString("FuncGenericSingletonHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Func.Generic.Singleton.SingleObject
        ///{
        ///    public partial class FuncGenericSingletonSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncGenericSingletonSingleObjectModule {
            get {
                return ResourceManager.GetString("FuncGenericSingletonSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Func.Generic.Transient.Hierarchy2
        ///{
        ///    public partial class FuncGenericTransientHierarchy2Module : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncGenericTransientHierarchy2Module {
            get {
                return ResourceManager.GetString("FuncGenericTransientHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Func.Generic.Transient.SingleObject
        ///{
        ///    public partial class FuncGenericTransientSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncGenericTransientSingleObjectModule {
            get {
                return ResourceManager.GetString("FuncGenericTransientSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Func.NonGeneric.Singleton.Hierarchy2
        ///{
        ///    public partial class FuncNonGenericSingletonHierarchy2Module : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncNonGenericSingletonHierarchy2Module {
            get {
                return ResourceManager.GetString("FuncNonGenericSingletonHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Func.NonGeneric.Singleton.SingleObject
        ///{
        ///    public partial class FuncNonGenericSingletonSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncNonGenericSingletonSingleObjectModule {
            get {
                return ResourceManager.GetString("FuncNonGenericSingletonSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Func.NonGeneric.Transient.Hierarchy2
        ///{
        ///    public partial class FuncNonGenericTransientHierarchy2Module : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncNonGenericTransientHierarchy2Module {
            get {
                return ResourceManager.GetString("FuncNonGenericTransientHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Func.NonGeneric.Transient.SingleObject
        ///{
        ///    public partial class FuncNonGenericTransientSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FuncNonGenericTransientSingleObjectModule {
            get {
                return ResourceManager.GetString("FuncNonGenericTransientSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Generic.IsRegisteredFrom
        ///{
        ///    public partial class GenericIsRegisteredFromModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericIsRegisteredFromModule {
            get {
                return ResourceManager.GetString("GenericIsRegisteredFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.InvalidToType
        ///{
        ///    public partial class InvalidToTypeTransientModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvalidToTypeTransientModule {
            get {
                return ResourceManager.GetString("InvalidToTypeTransientModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.LocalVariable
        ///{
        ///    public partial class LocalVariableTransientModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalVariableTransientModule {
            get {
                return ResourceManager.GetString("LocalVariableTransientModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.DifferentObjects
        ///{
        ///    public partial class NonGenericDifferentObjectsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .Wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericDifferentObjectsModule {
            get {
                return ResourceManager.GetString("NonGenericDifferentObjectsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.IncorrectRequest
        ///{
        ///    public partial class NonGenericIncorrectRequestModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericIncorrectRequestModule {
            get {
                return ResourceManager.GetString("NonGenericIncorrectRequestModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.SingleObject
        ///{
        ///    public partial class NonGenericSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericSingleObjectModule {
            get {
                return ResourceManager.GetString("NonGenericSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.TwoSameBindings
        ///{
        ///    public partial class NonGenericTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("NonGenericTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.Dispose
        ///{
        ///    public partial class SingletonDisposeModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScope()
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonDisposeModule {
            get {
                return ResourceManager.GetString("SingletonDisposeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Singleton.Hierarchy2
        ///{
        ///    public partial class SingletonHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonHierarchy2Module {
            get {
                return ResourceManager.GetString("SingletonHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using NuGet.Frameworks;
        ///
        ///namespace DpdtInject.Tests.Singleton.Hierarchy3
        ///{
        ///    public partial class SingletonHierarchy3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonHierarchy3Module {
            get {
                return ResourceManager.GetString("SingletonHierarchy3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.SingleObject
        ///{
        ///    public partial class SingletonSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingleto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonSingleObjectModule {
            get {
                return ResourceManager.GetString("SingletonSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection.PortableExecutable;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.SingleObjectWithArgument
        ///{
        ///    public partial class SingletonSingleObjectWithArgumentModule : DpdtModule
        ///    {
        ///        public con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonSingleObjectWithArgumentModule {
            get {
                return ResourceManager.GetString("SingletonSingleObjectWithArgumentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.TwoSameBindings
        ///{
        ///    public partial class SingletonTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("SingletonTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.UnknownRequest
        ///{
        ///    public partial class SingletonUnknownRequestModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonUnknownRequestModule {
            get {
                return ResourceManager.GetString("SingletonUnknownRequestModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Transient.Hierarchy2
        ///{
        ///    public partial class TransientHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientHierarchy2Module {
            get {
                return ResourceManager.GetString("TransientHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using NuGet.Frameworks;
        ///
        ///namespace DpdtInject.Tests.Transient.Hierarchy3
        ///{
        ///    public partial class TransientHierarchy3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientHierarchy3Module {
            get {
                return ResourceManager.GetString("TransientHierarchy3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.SingleObject
        ///{
        ///    public partial class TransientSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientSingleObjectModule {
            get {
                return ResourceManager.GetString("TransientSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection.PortableExecutable;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.SingleObjectWithArgument
        ///{
        ///    public partial class TransientSingleObjectWithArgumentModule : DpdtModule
        ///    {
        ///        public con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientSingleObjectWithArgumentModule {
            get {
                return ResourceManager.GetString("TransientSingleObjectWithArgumentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.TwoSameBindings
        ///{
        ///    public partial class TransientTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("TransientTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.CannotBeCasted
        ///{
        ///    public partial class UnsortedCannotBeCastedModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedCannotBeCastedModule {
            get {
                return ResourceManager.GetString("UnsortedCannotBeCastedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.CircularDependency3
        ///{
        ///    public partial class UnsortedCircularDependency3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedCircularDependency3Module {
            get {
                return ResourceManager.GetString("UnsortedCircularDependency3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///
        ///namespace DpdtInject.Tests.Unsorted.SameChildren
        ///{
        ///    public partial class UnsortedSameChildrenModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedSameChildrenModule {
            get {
                return ResourceManager.GetString("UnsortedSameChildrenModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.SingletonTransient
        ///{
        ///    public partial class UnsortedSingletonTransientModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public overr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedSingletonTransientModule {
            get {
                return ResourceManager.GetString("UnsortedSingletonTransientModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///
        ///namespace DpdtInject.Tests.Unsorted.TooManyChildren
        ///{
        ///    public partial class UnsortedTooManyChildrenModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some messag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedTooManyChildrenModule {
            get {
                return ResourceManager.GetString("UnsortedTooManyChildrenModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///
        ///namespace DpdtInject.Tests.Unsorted.UnknownDependency
        ///{
        ///    public partial class UnsortedUnknownDependencyModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedUnknownDependencyModule {
            get {
                return ResourceManager.GetString("UnsortedUnknownDependencyModule", resourceCulture);
            }
        }
    }
}
