//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpdtInject.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DpdtInject.Tests.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy2
        ///{
        ///    public partial class ConditionalHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy2Module {
            get {
                return ResourceManager.GetString("ConditionalHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy3First
        ///{
        ///    public partial class ConditionalHierarchy3FirstModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public overr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy3FirstModule {
            get {
                return ResourceManager.GetString("ConditionalHierarchy3FirstModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.Hierarchy3Second
        ///{
        ///    public partial class ConditionalHierarchy3SecondModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalHierarchy3SecondModule {
            get {
                return ResourceManager.GetString("ConditionalHierarchy3SecondModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.RContext.Hierarchy2
        ///{
        ///    public partial class ConditionalRContextHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalRContextHierarchy2Module {
            get {
                return ResourceManager.GetString("ConditionalRContextHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Conditional.RContext.Hierarchy2Variant1
        ///{
        ///    public partial class ConditionalRContextHierarchy2Variant1Module : DpdtModule
        ///    {
        ///        public const string BMessage = &quot;B some message [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalRContextHierarchy2Variant1Module {
            get {
                return ResourceManager.GetString("ConditionalRContextHierarchy2Variant1Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.SingleObject
        ///{
        ///    public partial class ConditionalSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA1&gt;()
        ///                . [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalSingleObjectModule {
            get {
                return ResourceManager.GetString("ConditionalSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.DifferentObjects
        ///{
        ///    public partial class NonGenericDifferentObjectsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .Wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericDifferentObjectsModule {
            get {
                return ResourceManager.GetString("NonGenericDifferentObjectsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.IncorrectRequest
        ///{
        ///    public partial class NonGenericIncorrectRequestModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericIncorrectRequestModule {
            get {
                return ResourceManager.GetString("NonGenericIncorrectRequestModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.SingleObject
        ///{
        ///    public partial class NonGenericSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericSingleObjectModule {
            get {
                return ResourceManager.GetString("NonGenericSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.NonGeneric.TwoSameBindings
        ///{
        ///    public partial class NonGenericTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("NonGenericTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.Dispose
        ///{
        ///    public partial class SingletonDisposeModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScope()
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonDisposeModule {
            get {
                return ResourceManager.GetString("SingletonDisposeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Singleton.Hierarchy2
        ///{
        ///    public partial class SingletonHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonHierarchy2Module {
            get {
                return ResourceManager.GetString("SingletonHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using NuGet.Frameworks;
        ///
        ///namespace DpdtInject.Tests.Singleton.Hierarchy3
        ///{
        ///    public partial class SingletonHierarchy3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonHierarchy3Module {
            get {
                return ResourceManager.GetString("SingletonHierarchy3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.SingleObject
        ///{
        ///    public partial class SingletonSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingleto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonSingleObjectModule {
            get {
                return ResourceManager.GetString("SingletonSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection.PortableExecutable;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.SingleObjectWithArgument
        ///{
        ///    public partial class SingletonSingleObjectWithArgumentModule : DpdtModule
        ///    {
        ///        public con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonSingleObjectWithArgumentModule {
            get {
                return ResourceManager.GetString("SingletonSingleObjectWithArgumentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Singleton.TwoSameBindings
        ///{
        ///    public partial class SingletonTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("SingletonTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Transient.Hierarchy2
        ///{
        ///    public partial class TransientHierarchy2Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientHierarchy2Module {
            get {
                return ResourceManager.GetString("TransientHierarchy2Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using NuGet.Frameworks;
        ///
        ///namespace DpdtInject.Tests.Transient.Hierarchy3
        ///{
        ///    public partial class TransientHierarchy3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientHierarchy3Module {
            get {
                return ResourceManager.GetString("TransientHierarchy3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.SingleObject
        ///{
        ///    public partial class TransientSingleObjectModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientSingleObjectModule {
            get {
                return ResourceManager.GetString("TransientSingleObjectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Reflection.PortableExecutable;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.SingleObjectWithArgument
        ///{
        ///    public partial class TransientSingleObjectWithArgumentModule : DpdtModule
        ///    {
        ///        public con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientSingleObjectWithArgumentModule {
            get {
                return ResourceManager.GetString("TransientSingleObjectWithArgumentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Transient.TwoSameBindings
        ///{
        ///    public partial class TransientTwoSameBindingsModule : DpdtModule
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransientTwoSameBindingsModule {
            get {
                return ResourceManager.GetString("TransientTwoSameBindingsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.CircularDependency3
        ///{
        ///    public partial class UnsortedCircularDependency3Module : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedCircularDependency3Module {
            get {
                return ResourceManager.GetString("UnsortedCircularDependency3Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.SingletonTransient
        ///{
        ///    public partial class UnsortedSingletonTransientModule : DpdtModule
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public overr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedSingletonTransientModule {
            get {
                return ResourceManager.GetString("UnsortedSingletonTransientModule", resourceCulture);
            }
        }
    }
}
