//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpdtInject.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DpdtInject.Tests.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren0
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren0_Cluster : DefaultCluster
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren0_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren1
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren1_Cluster : DefaultCluster
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren1_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren2
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren2_Cluster : DefaultCluster
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren2_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyChildren3
        ///{
        ///    public partial class ActivationExcessiveTooManyChildren3_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyChildren3_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyChildren3_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots0
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots0_Cluste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots0_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots1
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots1_Cluste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots1_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots2
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots2_Cluste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots2_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Excp;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///
        ///namespace DpdtInject.Tests.Activation.Excessive.TooManyRoots3
        ///{
        ///    public partial class ActivationExcessiveTooManyRoots3_Cluste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationExcessiveTooManyRoots3_Cluster {
            get {
                return ResourceManager.GetString("ActivationExcessiveTooManyRoots3_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.Generic.Different
        ///{
        ///    public partial class ClusterGenericDifferent_RootCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                ;
        ///        } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterGenericDifferent_Cluster {
            get {
                return ResourceManager.GetString("ClusterGenericDifferent_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.Generic.DifferentConditional0
        ///{
        ///    public partial class ClusterGenericDifferentConditional0_FirstCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterGenericDifferentConditional0_Cluster {
            get {
                return ResourceManager.GetString("ClusterGenericDifferentConditional0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.Generic.DifferentConditional1
        ///{
        ///    public partial class ClusterGenericDifferentConditional1_FirstCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterGenericDifferentConditional1_Cluster {
            get {
                return ResourceManager.GetString("ClusterGenericDifferentConditional1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.Generic.DifferentFunc
        ///{
        ///    public partial class ClusterGenericDifferentFunc_RootCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                ;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterGenericDifferentFunc_Cluster {
            get {
                return ResourceManager.GetString("ClusterGenericDifferentFunc_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.NonGeneric.Different
        ///{
        ///    public partial class ClusterNonGenericDifferent_RootCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                ;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterNonGenericDifferent_Cluster {
            get {
                return ResourceManager.GetString("ClusterNonGenericDifferent_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.NonGeneric.DifferentConditional0
        ///{
        ///    public partial class ClusterNonGenericDifferentConditional0_FirstCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterNonGenericDifferentConditional0_Cluster {
            get {
                return ResourceManager.GetString("ClusterNonGenericDifferentConditional0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.NonGeneric.DifferentConditional1
        ///{
        ///    public partial class ClusterNonGenericDifferentConditional1_FirstCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterNonGenericDifferentConditional1_Cluster {
            get {
                return ResourceManager.GetString("ClusterNonGenericDifferentConditional1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Cluster.NonGeneric.DifferentFunc
        ///{
        ///    public partial class ClusterNonGenericDifferentFunc_RootCluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClusterNonGenericDifferentFunc_Cluster {
            get {
                return ResourceManager.GetString("ClusterNonGenericDifferentFunc_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.Generic.Hierarchy2
        ///{
        ///    public partial class ConditionalGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///                .WithTransientScope()
        ///                .When [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ConditionalGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.Generic.Hierarchy2SameConstant
        ///{
        ///    public partial class ConditionalGenericHierarchy2SameConstant_Cluster : DefaultCluster
        ///    {
        ///        public static A ConstantA1 = new A();
        ///        public static A ConstantA2 = new A();
        ///
        ///        public override void Load()
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalGenericHierarchy2SameConstant_Cluster {
            get {
                return ResourceManager.GetString("ConditionalGenericHierarchy2SameConstant_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.Generic.Hierarchy3First
        ///{
        ///    public partial class ConditionalGenericHierarchy3First_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalGenericHierarchy3First_Cluster {
            get {
                return ResourceManager.GetString("ConditionalGenericHierarchy3First_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.Generic.Hierarchy3Second
        ///{
        ///    public partial class ConditionalGenericHierarchy3Second_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalGenericHierarchy3Second_Cluster {
            get {
                return ResourceManager.GetString("ConditionalGenericHierarchy3Second_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.Generic.OnlyOneInMiddle
        ///{
        ///    public partial class ConditionalGenericOnlyOneInMiddle_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalGenericOnlyOneInMiddle_Cluster {
            get {
                return ResourceManager.GetString("ConditionalGenericOnlyOneInMiddle_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.NonGeneric.Hierarchy2
        ///{
        ///    public partial class ConditionalNonGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///                .WithTransientScope()
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalNonGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ConditionalNonGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.NonGeneric.Hierarchy2SameConstant
        ///{
        ///    public partial class ConditionalNonGenericHierarchy2SameConstant_Cluster : DefaultCluster
        ///    {
        ///        public static A ConstantA1 = new A();
        ///        public static A ConstantA2 = new A();
        ///
        ///        public override void Load [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalNonGenericHierarchy2SameConstant_Cluster {
            get {
                return ResourceManager.GetString("ConditionalNonGenericHierarchy2SameConstant_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.NonGeneric.Hierarchy3First
        ///{
        ///    public partial class ConditionalNonGenericHierarchy3First_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalNonGenericHierarchy3First_Cluster {
            get {
                return ResourceManager.GetString("ConditionalNonGenericHierarchy3First_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.NonGeneric.Hierarchy3Second
        ///{
        ///    public partial class ConditionalNonGenericHierarchy3Second_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalNonGenericHierarchy3Second_Cluster {
            get {
                return ResourceManager.GetString("ConditionalNonGenericHierarchy3Second_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Conditional.NonGeneric.OnlyOneInMiddle
        ///{
        ///    public partial class ConditionalNonGenericOnlyOneInMiddle_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionalNonGenericOnlyOneInMiddle_Cluster {
            get {
                return ResourceManager.GetString("ConditionalNonGenericOnlyOneInMiddle_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Factory.ConstructorArgument0
        ///{
        ///    public partial class FactoryConstructorArgument0_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IAFactory&gt;()
        ///                .ToFactory&lt;AFactory, A&gt;()
        ///                .WithSingletonScope()
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactoryConstructorArgument0_Cluster {
            get {
                return ResourceManager.GetString("FactoryConstructorArgument0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Factory.Simple0
        ///{
        ///    public partial class FactorySimple0_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IAFactory&gt;()
        ///                .ToFactory&lt;AFactory, A&gt;()
        ///                .WithSingletonScope()
        ///                ;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactorySimple0_Cluster {
            get {
                return ResourceManager.GetString("FactorySimple0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Factory.UnknownConstructorArgument0
        ///{
        ///    public partial class FactoryUnknownConstructorArgument0_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IAFactory&gt;()
        ///                .ToFactory&lt;AF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactoryUnknownConstructorArgument0_Cluster {
            get {
                return ResourceManager.GetString("FactoryUnknownConstructorArgument0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Factory.UnknownConstructorArgument1
        ///{
        ///    public partial class FactoryUnknownConstructorArgument1_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IAFactory&gt;()
        ///                .ToFactory&lt;AF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactoryUnknownConstructorArgument1_Cluster {
            get {
                return ResourceManager.GetString("FactoryUnknownConstructorArgument1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Factory.UnrelatedMethod
        ///{
        ///    public partial class FactoryUnrelatedMethod_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IAFactory&gt;()
        ///                .ToFactory&lt;AFactory, A&gt;()
        ///                .WithSingletonScope()
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactoryUnrelatedMethod_Cluster {
            get {
                return ResourceManager.GetString("FactoryUnrelatedMethod_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.Hierarchy2Conditional
        ///{
        ///    public partial class GetAllGenericHierarchy2Conditional_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IZ&gt;()
        ///                .To&lt;Z&gt;()
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericHierarchy2Conditional_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericHierarchy2Conditional_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.NoBinding
        ///{
        ///    public partial class GetAllGenericNoBinding_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            //nothing!
        ///        }
        ///
        ///        public class GetAllGenericNoBinding_ClusterTe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericNoBinding_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericNoBinding_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.SingleObject
        ///{
        ///    public partial class GetAllGenericSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericSingleObject_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.TwoObjects
        ///{
        ///    public partial class GetAllGenericTwoObjects_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///                .WithSingletonScope() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericTwoObjects_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericTwoObjects_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.TwoObjectsConditional0
        ///{
        ///    public partial class GetAllGenericTwoObjectsConditional0_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericTwoObjectsConditional0_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericTwoObjectsConditional0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.Generic.TwoObjectsConditional1
        ///{
        ///    public partial class GetAllGenericTwoObjectsConditional1_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllGenericTwoObjectsConditional1_Cluster {
            get {
                return ResourceManager.GetString("GetAllGenericTwoObjectsConditional1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.Hierarchy2Conditional
        ///{
        ///    public partial class GetAllNonGenericHierarchy2Conditional_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IZ&gt;()
        ///                .To&lt;Z&gt;()
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericHierarchy2Conditional_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericHierarchy2Conditional_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.NoBinding
        ///{
        ///    public partial class GetAllNonGenericNoBinding_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            //nothing!
        ///        }
        ///
        ///        public class GetAllNonGenericNoBinding_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericNoBinding_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericNoBinding_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.SingleObject
        ///{
        ///    public partial class GetAllNonGenericSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSinglet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericSingleObject_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.TwoObjects
        ///{
        ///    public partial class GetAllNonGenericTwoObjects_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///                .WithSingletonS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericTwoObjects_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericTwoObjects_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.TwoObjectsConditional0
        ///{
        ///    public partial class GetAllNonGenericTwoObjectsConditional0_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericTwoObjectsConditional0_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericTwoObjectsConditional0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.GetAll.NonGeneric.TwoObjectsConditional1
        ///{
        ///    public partial class GetAllNonGenericTwoObjectsConditional1_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllNonGenericTwoObjectsConditional1_Cluster {
            get {
                return ResourceManager.GetString("GetAllNonGenericTwoObjectsConditional1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.NonGeneric.IncorrectRequest
        ///{
        ///    public partial class NonGenericIncorrectRequest_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonGenericIncorrectRequest_Cluster {
            get {
                return ResourceManager.GetString("NonGenericIncorrectRequest_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Constant.Generic.SingleInterfaceSingleObject
        ///{
        ///    public partial class ScopeConstantGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        private static readonly A AInstance = new A();
        ///
        ///        public override void Load()
        ///        {
        ///            Bi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeConstantGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeConstantGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Constant.NonGeneric.SingleInterfaceSingleObject
        ///{
        ///    public partial class ScopeConstantNonGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        private static readonly A AInstance = new A();
        ///
        ///        public override void Load()
        ///        {
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeConstantNonGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeConstantNonGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Module.RContext;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.Generic.Hierarchy2
        ///{
        ///    public partial class ScopeCustomGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public const  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Module.RContext;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.Generic.Hierarchy2DifferentCluster
        ///{
        ///    public partial class ScopeCustomGenericHierarchy2DifferentCluster_FirstCluster : Default [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomGenericHierarchy2DifferentCluster_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomGenericHierarchy2DifferentCluster_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.RContext;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.Generic.SingleObject
        ///{
        ///    public partial class ScopeCustomGenericSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomGenericSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomGenericSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Module.RContext;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.NonGeneric.Hierarchy2
        ///{
        ///    public partial class ScopeCustomNonGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomNonGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomNonGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///using DpdtInject.Injector.Module.RContext;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.NonGeneric.Hierarchy2DifferentCluster
        ///{
        ///    public partial class ScopeCustomNonGenericHierarchy2DifferentCluster_FirstCluster : D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomNonGenericHierarchy2DifferentCluster_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomNonGenericHierarchy2DifferentCluster_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module;
        ///using DpdtInject.Injector.Module.RContext;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///
        ///namespace DpdtInject.Tests.Scope.Custom.NonGeneric.SingleObject
        ///{
        ///    public partial class ScopeCustomNonGenericSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public ove [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeCustomNonGenericSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeCustomNonGenericSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.Generic.Hierarchy2
        ///{
        ///    public partial class ScopeSingletonGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScope()
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.Generic.SingleInterfaceSingleObject
        ///{
        ///    public partial class ScopeSingletonGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .Wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.Generic.SingleObjectDefinedArgument
        ///{
        ///    public partial class ScopeSingletonGenericSingleObjectDefinedArgument_Cluster : DefaultCluster
        ///    {
        ///        const string CustomMesage = &quot;custom message&quot;;
        ///
        ///        public overri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonGenericSingleObjectDefinedArgument_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonGenericSingleObjectDefinedArgument_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.Generic.TwoInterfacesSingleObject
        ///{
        ///    public partial class ScopeSingletonGenericTwoInterfacesSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA0, IA1&gt;()
        ///                .To&lt;A&gt;()
        ///                .W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonGenericTwoInterfacesSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonGenericTwoInterfacesSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.NonGeneric.Hierarchy2
        ///{
        ///    public partial class ScopeSingletonNonGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScope()
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonNonGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonNonGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.NonGeneric.SingleInterfaceSingleObject
        ///{
        ///    public partial class ScopeSingletonNonGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonNonGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonNonGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.NonGeneric.TwoInterfacesSingleObject
        ///{
        ///    public partial class ScopeSingletonNonGenericTwoInterfacesSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA0, IA1&gt;()
        ///                .To&lt;A&gt;()
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeSingletonNonGenericTwoInterfacesSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeSingletonNonGenericTwoInterfacesSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Transient.Generic.Hierarchy2
        ///{
        ///    public partial class ScopeTransientGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeTransientGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("ScopeTransientGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Transient.Generic.SingleInterfaceSingleObject
        ///{
        ///    public partial class ScopeTransientGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .Wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeTransientGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeTransientGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Transient.Generic.SingleObjectDefinedArgument
        ///{
        ///    public partial class ScopeTransientGenericSingleObjectDefinedArgument_Cluster : DefaultCluster
        ///    {
        ///        const string CustomMesage = &quot;custom message&quot;;
        ///
        ///        public overri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeTransientGenericSingleObjectDefinedArgument_Cluster {
            get {
                return ResourceManager.GetString("ScopeTransientGenericSingleObjectDefinedArgument_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Transient.Generic.TwoInterfacesSingleObject
        ///{
        ///    public partial class ScopeTransientGenericTwoInterfacesSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA0, IA1&gt;()
        ///                .To&lt;A&gt;()
        ///                .W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScopeTransientGenericTwoInterfacesSingleObject_Cluster {
            get {
                return ResourceManager.GetString("ScopeTransientGenericTwoInterfacesSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Scope.Singleton.Dispose
        ///{
        ///    public partial class SingletonDispose_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingletonDispose_Cluster {
            get {
                return ResourceManager.GetString("SingletonDispose_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.CannotBeCasted
        ///{
        ///    public partial class UnsortedCannotBeCasted_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedCannotBeCasted_Cluster {
            get {
                return ResourceManager.GetString("UnsortedCannotBeCasted_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Module;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using DpdtInject.Injector.Module.Bind;
        ///
        ///namespace DpdtInject.Tests.Unsorted.CircularDependency3
        ///{
        ///    public partial class UnsortedCircularDependency3_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedCircularDependency3_Cluster {
            get {
                return ResourceManager.GetString("UnsortedCircularDependency3_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.ComplexTypeArgument0
        ///{
        ///    public partial class UnsortedComplexTypeArgument0_Cluster : DefaultCluster
        ///    {
        ///        public static Func&lt;Func&lt;object&gt;, Func&lt;string&gt;&gt; Funca =&gt;
        ///            fo =&gt; new  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedComplexTypeArgument0_Cluster {
            get {
                return ResourceManager.GetString("UnsortedComplexTypeArgument0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.Generic.IsRegistered
        ///{
        ///    public partial class UnsortedGenericIsRegistered_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransient [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedGenericIsRegistered_Cluster {
            get {
                return ResourceManager.GetString("UnsortedGenericIsRegistered_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.InvalidToType
        ///{
        ///    public partial class UnsortedInvalidToType_Cluster : DefaultCluster
        ///    {
        ///        public const string Message = &quot;some message&quot;;
        ///
        ///        public override void Load()
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedInvalidToType_Cluster {
            get {
                return ResourceManager.GetString("UnsortedInvalidToType_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.NativeTypeArgument0
        ///{
        ///    public partial class UnsortedNativeTypeArgument0_Cluster : DefaultCluster
        ///    {
        ///        public const string DefaultMessage = &quot;default message&quot;;
        ///
        ///        public overrid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedNativeTypeArgument0_Cluster {
            get {
                return ResourceManager.GetString("UnsortedNativeTypeArgument0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.NonGeneric.IsRegistered
        ///{
        ///    public partial class UnsortedNonGenericIsRegistered_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedNonGenericIsRegistered_Cluster {
            get {
                return ResourceManager.GetString("UnsortedNonGenericIsRegistered_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.OptionalArgument0
        ///{
        ///    public partial class UnsortedOptionalArgument0_Cluster : DefaultCluster
        ///    {
        ///        public const string DefaultMessage = &quot;default message&quot;;
        ///        public const string  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedOptionalArgument0_Cluster {
            get {
                return ResourceManager.GetString("UnsortedOptionalArgument0_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.OptionalArgument1
        ///{
        ///    public partial class UnsortedOptionalArgument1_Cluster : DefaultCluster
        ///    {
        ///        public const string DefaultMessage = &quot;default message&quot;;
        ///
        ///        public override vo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedOptionalArgument1_Cluster {
            get {
                return ResourceManager.GetString("UnsortedOptionalArgument1_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.SingletonCustom
        ///{
        ///    public partial class UnsortedSingletonCustom_Cluster : DefaultCluster
        ///    {
        ///        public const string DefaultMessage = &quot;default message&quot;;
        ///
        ///        public override void L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedSingletonCustom_Cluster {
            get {
                return ResourceManager.GetString("UnsortedSingletonCustom_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Module.Bind;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.SingletonTransient
        ///{
        ///    public partial class UnsortedSingletonTransient_Cluster : DefaultCluster
        ///    {
        ///        public const string DefaultMessage = &quot;default message&quot;;
        ///
        ///        public override  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedSingletonTransient_Cluster {
            get {
                return ResourceManager.GetString("UnsortedSingletonTransient_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using DpdtInject.Injector.Excp;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Unsorted.TooManyChildren
        ///{
        ///    public partial class UnsortedTooManyChildren_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A0&gt;()
        ///                .WithTransientScope()        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnsortedTooManyChildren_Cluster {
            get {
                return ResourceManager.GetString("UnsortedTooManyChildren_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.Generic.DeclaredFunc
        ///{
        ///    public partial class WrapperFuncGenericDeclaredFunc_Cluster : DefaultCluster
        ///    {
        ///        public static readonly A AInstance = new A();
        ///        public static readonly Func&lt;IA&gt; Funca = () =&gt; AInstance;
        ///
        ///        public override void Lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncGenericDeclaredFunc_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncGenericDeclaredFunc_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.Generic.Hierarchy2
        ///{
        ///    public partial class WrapperFuncGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                ;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.Generic.SingleInterfaceSingleObject
        ///{
        ///    public partial class WrapperFuncGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTrans [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.NonGeneric.DeclaredFunc
        ///{
        ///    public partial class WrapperFuncNonGenericDeclaredFunc_Cluster : DefaultCluster
        ///    {
        ///        public static readonly A AInstance = new A();
        ///        public static readonly Func&lt;IA&gt; Funca = () =&gt; AInstance;
        ///
        ///        public override v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncNonGenericDeclaredFunc_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncNonGenericDeclaredFunc_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.NonGeneric.Hierarchy2
        ///{
        ///    public partial class WrapperFuncNonGenericHierarchy2_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithTransientScope()
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncNonGenericHierarchy2_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncNonGenericHierarchy2_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.NonGeneric.SingleInterfaceSingleObject
        ///{
        ///    public partial class WrapperFuncNonGenericSingleInterfaceSingleObject_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .Wit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncNonGenericSingleInterfaceSingleObject_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncNonGenericSingleInterfaceSingleObject_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DpdtInject.Injector;
        ///using Microsoft.VisualStudio.TestTools.UnitTesting;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace DpdtInject.Tests.Wrapper.Func.Singleton
        ///{
        ///    public partial class WrapperFuncSingleton_Cluster : DefaultCluster
        ///    {
        ///        public override void Load()
        ///        {
        ///            Bind&lt;IA&gt;()
        ///                .To&lt;A&gt;()
        ///                .WithSingletonScope()
        ///                ;
        ///
        ///        }
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperFuncSingleton_Cluster {
            get {
                return ResourceManager.GetString("WrapperFuncSingleton_Cluster", resourceCulture);
            }
        }
    }
}
