// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DpdtInject.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
//        public const string guidAdjustNamespacePackageString = "19967834-2536-4a51-82f7-e607434734d2";
//        public static Guid guidAdjustNamespacePackage = new Guid(guidAdjustNamespacePackageString);

//        public const string guidAdjustNamespacePackageCmdSetString = "3f7538ed-5c20-4d49-89fc-c401bb76df25";
//        public static Guid guidAdjustNamespacePackageCmdSet = new Guid(guidAdjustNamespacePackageCmdSetString);

//        public const string guidImagesString = "6309e701-5f02-4bc7-8376-02ec55028dbf";
//        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
//        public const int MyMenuGroup = 0x1020;
//        public const int DoAdjustCommandId = 0x0100;
//        public const int dispersion16 = 0x0001;
    }
}
