//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DpdtInject.Generator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DpdtInject.Generator.Core.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma warning disable CS0105
        ///using DpdtInject.Injector;
        ///using DpdtInject.Injector.CustomScope;
        ///using DpdtInject.Injector.Excp;
        ///using DpdtInject.Injector.Reinvented;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Runtime.CompilerServices;
        ///using System.Threading;
        ///using DpdtInject.Injector.RContext;
        ///// ReSharper disable SuspiciousTypeConversion.Global
        ///
        /////GENERATOR: place for an additional usings
        ///
        ///namespace DpdtInject.Generator
        ///{
        ///#nullable  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarcassCluster {
            get {
                return ResourceManager.GetString("CarcassCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma warning disable CS0105
        ///using System;
        ///using System.Diagnostics;
        ///using System.Runtime.CompilerServices;
        ///using BindFromType = System.Object;
        ///using SessionSaver = DpdtInject.Injector.Bind.BaseSessionSaver;
        ///// ReSharper disable SuspiciousTypeConversion.Global
        ///
        ///namespace DpdtInject.Generator
        ///{
        ///    public partial class CarcassProxy
        ///        : BindFromType
        ///    {
        ///        private static readonly double _stopwatchFrequency = (double)Stopwatch.Frequency;
        ///
        ///        private readonly BindFromType _pay [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarcassProxy {
            get {
                return ResourceManager.GetString("CarcassProxy", resourceCulture);
            }
        }
    }
}
