//seed: -624853138
using DpdtInject.Injector;
using DpdtInject.Injector.Excp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using DryIoc;

namespace DpdtInject.Tests.Performance.TimeConsume.BigTree0
{
    public static class DryIocRelated
    {
        public const int BindCount = 100;
        public const string BindCountString = "100";
        public const string TestPrefix = "NonGenericSingleton100";
        public static void Bind(Container container)
        {
#region bind code
            container.Register<IInterface0, Class0>(Reuse.Singleton);
            container.Register<IInterface1, Class1>(Reuse.Singleton);
            container.Register<IInterface2, Class2>(Reuse.Singleton);
            container.Register<IInterface3, Class3>(Reuse.Singleton);
            container.Register<IInterface4, Class4>(Reuse.Singleton);
            container.Register<IInterface5, Class5>(Reuse.Singleton);
            container.Register<IInterface6, Class6>(Reuse.Singleton);
            container.Register<IInterface7, Class7>(Reuse.Singleton);
            container.Register<IInterface8, Class8>(Reuse.Singleton);
            container.Register<IInterface9, Class9>(Reuse.Singleton);
            container.Register<IInterface10, Class10>(Reuse.Singleton);
            container.Register<IInterface11, Class11>(Reuse.Singleton);
            container.Register<IInterface12, Class12>(Reuse.Singleton);
            container.Register<IInterface13, Class13>(Reuse.Singleton);
            container.Register<IInterface14, Class14>(Reuse.Singleton);
            container.Register<IInterface15, Class15>(Reuse.Singleton);
            container.Register<IInterface16, Class16>(Reuse.Singleton);
            container.Register<IInterface17, Class17>(Reuse.Singleton);
            container.Register<IInterface18, Class18>(Reuse.Singleton);
            container.Register<IInterface19, Class19>(Reuse.Singleton);
            container.Register<IInterface20, Class20>(Reuse.Singleton);
            container.Register<IInterface21, Class21>(Reuse.Singleton);
            container.Register<IInterface22, Class22>(Reuse.Singleton);
            container.Register<IInterface23, Class23>(Reuse.Singleton);
            container.Register<IInterface24, Class24>(Reuse.Singleton);
            container.Register<IInterface25, Class25>(Reuse.Singleton);
            container.Register<IInterface26, Class26>(Reuse.Singleton);
            container.Register<IInterface27, Class27>(Reuse.Singleton);
            container.Register<IInterface28, Class28>(Reuse.Singleton);
            container.Register<IInterface29, Class29>(Reuse.Singleton);
            container.Register<IInterface30, Class30>(Reuse.Singleton);
            container.Register<IInterface31, Class31>(Reuse.Singleton);
            container.Register<IInterface32, Class32>(Reuse.Singleton);
            container.Register<IInterface33, Class33>(Reuse.Singleton);
            container.Register<IInterface34, Class34>(Reuse.Singleton);
            container.Register<IInterface35, Class35>(Reuse.Singleton);
            container.Register<IInterface36, Class36>(Reuse.Singleton);
            container.Register<IInterface37, Class37>(Reuse.Singleton);
            container.Register<IInterface38, Class38>(Reuse.Singleton);
            container.Register<IInterface39, Class39>(Reuse.Singleton);
            container.Register<IInterface40, Class40>(Reuse.Singleton);
            container.Register<IInterface41, Class41>(Reuse.Singleton);
            container.Register<IInterface42, Class42>(Reuse.Singleton);
            container.Register<IInterface43, Class43>(Reuse.Singleton);
            container.Register<IInterface44, Class44>(Reuse.Singleton);
            container.Register<IInterface45, Class45>(Reuse.Singleton);
            container.Register<IInterface46, Class46>(Reuse.Singleton);
            container.Register<IInterface47, Class47>(Reuse.Singleton);
            container.Register<IInterface48, Class48>(Reuse.Singleton);
            container.Register<IInterface49, Class49>(Reuse.Singleton);
            container.Register<IInterface50, Class50>(Reuse.Singleton);
            container.Register<IInterface51, Class51>(Reuse.Singleton);
            container.Register<IInterface52, Class52>(Reuse.Singleton);
            container.Register<IInterface53, Class53>(Reuse.Singleton);
            container.Register<IInterface54, Class54>(Reuse.Singleton);
            container.Register<IInterface55, Class55>(Reuse.Singleton);
            container.Register<IInterface56, Class56>(Reuse.Singleton);
            container.Register<IInterface57, Class57>(Reuse.Singleton);
            container.Register<IInterface58, Class58>(Reuse.Singleton);
            container.Register<IInterface59, Class59>(Reuse.Singleton);
            container.Register<IInterface60, Class60>(Reuse.Singleton);
            container.Register<IInterface61, Class61>(Reuse.Singleton);
            container.Register<IInterface62, Class62>(Reuse.Singleton);
            container.Register<IInterface63, Class63>(Reuse.Singleton);
            container.Register<IInterface64, Class64>(Reuse.Singleton);
            container.Register<IInterface65, Class65>(Reuse.Singleton);
            container.Register<IInterface66, Class66>(Reuse.Singleton);
            container.Register<IInterface67, Class67>(Reuse.Singleton);
            container.Register<IInterface68, Class68>(Reuse.Singleton);
            container.Register<IInterface69, Class69>(Reuse.Singleton);
            container.Register<IInterface70, Class70>(Reuse.Singleton);
            container.Register<IInterface71, Class71>(Reuse.Singleton);
            container.Register<IInterface72, Class72>(Reuse.Singleton);
            container.Register<IInterface73, Class73>(Reuse.Singleton);
            container.Register<IInterface74, Class74>(Reuse.Singleton);
            container.Register<IInterface75, Class75>(Reuse.Singleton);
            container.Register<IInterface76, Class76>(Reuse.Singleton);
            container.Register<IInterface77, Class77>(Reuse.Singleton);
            container.Register<IInterface78, Class78>(Reuse.Singleton);
            container.Register<IInterface79, Class79>(Reuse.Singleton);
            container.Register<IInterface80, Class80>(Reuse.Singleton);
            container.Register<IInterface81, Class81>(Reuse.Singleton);
            container.Register<IInterface82, Class82>(Reuse.Singleton);
            container.Register<IInterface83, Class83>(Reuse.Singleton);
            container.Register<IInterface84, Class84>(Reuse.Singleton);
            container.Register<IInterface85, Class85>(Reuse.Singleton);
            container.Register<IInterface86, Class86>(Reuse.Singleton);
            container.Register<IInterface87, Class87>(Reuse.Singleton);
            container.Register<IInterface88, Class88>(Reuse.Singleton);
            container.Register<IInterface89, Class89>(Reuse.Singleton);
            container.Register<IInterface90, Class90>(Reuse.Singleton);
            container.Register<IInterface91, Class91>(Reuse.Singleton);
            container.Register<IInterface92, Class92>(Reuse.Singleton);
            container.Register<IInterface93, Class93>(Reuse.Singleton);
            container.Register<IInterface94, Class94>(Reuse.Singleton);
            container.Register<IInterface95, Class95>(Reuse.Singleton);
            container.Register<IInterface96, Class96>(Reuse.Singleton);
            container.Register<IInterface97, Class97>(Reuse.Singleton);
            container.Register<IInterface98, Class98>(Reuse.Singleton);
            container.Register<IInterface99, Class99>(Reuse.Singleton);
            ;
#endregion
        }

        public static void Resolve(Container container)
        {
#region resolution code
            var resolvedInstance0 = container.Resolve(typeof(IInterface0));
            var resolvedInstance1 = container.Resolve(typeof(IInterface1));
            var resolvedInstance2 = container.Resolve(typeof(IInterface2));
            var resolvedInstance3 = container.Resolve(typeof(IInterface3));
            var resolvedInstance4 = container.Resolve(typeof(IInterface4));
            var resolvedInstance5 = container.Resolve(typeof(IInterface5));
            var resolvedInstance6 = container.Resolve(typeof(IInterface6));
            var resolvedInstance7 = container.Resolve(typeof(IInterface7));
            var resolvedInstance8 = container.Resolve(typeof(IInterface8));
            var resolvedInstance9 = container.Resolve(typeof(IInterface9));
            var resolvedInstance10 = container.Resolve(typeof(IInterface10));
            var resolvedInstance11 = container.Resolve(typeof(IInterface11));
            var resolvedInstance12 = container.Resolve(typeof(IInterface12));
            var resolvedInstance13 = container.Resolve(typeof(IInterface13));
            var resolvedInstance14 = container.Resolve(typeof(IInterface14));
            var resolvedInstance15 = container.Resolve(typeof(IInterface15));
            var resolvedInstance16 = container.Resolve(typeof(IInterface16));
            var resolvedInstance17 = container.Resolve(typeof(IInterface17));
            var resolvedInstance18 = container.Resolve(typeof(IInterface18));
            var resolvedInstance19 = container.Resolve(typeof(IInterface19));
            var resolvedInstance20 = container.Resolve(typeof(IInterface20));
            var resolvedInstance21 = container.Resolve(typeof(IInterface21));
            var resolvedInstance22 = container.Resolve(typeof(IInterface22));
            var resolvedInstance23 = container.Resolve(typeof(IInterface23));
            var resolvedInstance24 = container.Resolve(typeof(IInterface24));
            var resolvedInstance25 = container.Resolve(typeof(IInterface25));
            var resolvedInstance26 = container.Resolve(typeof(IInterface26));
            var resolvedInstance27 = container.Resolve(typeof(IInterface27));
            var resolvedInstance28 = container.Resolve(typeof(IInterface28));
            var resolvedInstance29 = container.Resolve(typeof(IInterface29));
            var resolvedInstance30 = container.Resolve(typeof(IInterface30));
            var resolvedInstance31 = container.Resolve(typeof(IInterface31));
            var resolvedInstance32 = container.Resolve(typeof(IInterface32));
            var resolvedInstance33 = container.Resolve(typeof(IInterface33));
            var resolvedInstance34 = container.Resolve(typeof(IInterface34));
            var resolvedInstance35 = container.Resolve(typeof(IInterface35));
            var resolvedInstance36 = container.Resolve(typeof(IInterface36));
            var resolvedInstance37 = container.Resolve(typeof(IInterface37));
            var resolvedInstance38 = container.Resolve(typeof(IInterface38));
            var resolvedInstance39 = container.Resolve(typeof(IInterface39));
            var resolvedInstance40 = container.Resolve(typeof(IInterface40));
            var resolvedInstance41 = container.Resolve(typeof(IInterface41));
            var resolvedInstance42 = container.Resolve(typeof(IInterface42));
            var resolvedInstance43 = container.Resolve(typeof(IInterface43));
            var resolvedInstance44 = container.Resolve(typeof(IInterface44));
            var resolvedInstance45 = container.Resolve(typeof(IInterface45));
            var resolvedInstance46 = container.Resolve(typeof(IInterface46));
            var resolvedInstance47 = container.Resolve(typeof(IInterface47));
            var resolvedInstance48 = container.Resolve(typeof(IInterface48));
            var resolvedInstance49 = container.Resolve(typeof(IInterface49));
            var resolvedInstance50 = container.Resolve(typeof(IInterface50));
            var resolvedInstance51 = container.Resolve(typeof(IInterface51));
            var resolvedInstance52 = container.Resolve(typeof(IInterface52));
            var resolvedInstance53 = container.Resolve(typeof(IInterface53));
            var resolvedInstance54 = container.Resolve(typeof(IInterface54));
            var resolvedInstance55 = container.Resolve(typeof(IInterface55));
            var resolvedInstance56 = container.Resolve(typeof(IInterface56));
            var resolvedInstance57 = container.Resolve(typeof(IInterface57));
            var resolvedInstance58 = container.Resolve(typeof(IInterface58));
            var resolvedInstance59 = container.Resolve(typeof(IInterface59));
            var resolvedInstance60 = container.Resolve(typeof(IInterface60));
            var resolvedInstance61 = container.Resolve(typeof(IInterface61));
            var resolvedInstance62 = container.Resolve(typeof(IInterface62));
            var resolvedInstance63 = container.Resolve(typeof(IInterface63));
            var resolvedInstance64 = container.Resolve(typeof(IInterface64));
            var resolvedInstance65 = container.Resolve(typeof(IInterface65));
            var resolvedInstance66 = container.Resolve(typeof(IInterface66));
            var resolvedInstance67 = container.Resolve(typeof(IInterface67));
            var resolvedInstance68 = container.Resolve(typeof(IInterface68));
            var resolvedInstance69 = container.Resolve(typeof(IInterface69));
            var resolvedInstance70 = container.Resolve(typeof(IInterface70));
            var resolvedInstance71 = container.Resolve(typeof(IInterface71));
            var resolvedInstance72 = container.Resolve(typeof(IInterface72));
            var resolvedInstance73 = container.Resolve(typeof(IInterface73));
            var resolvedInstance74 = container.Resolve(typeof(IInterface74));
            var resolvedInstance75 = container.Resolve(typeof(IInterface75));
            var resolvedInstance76 = container.Resolve(typeof(IInterface76));
            var resolvedInstance77 = container.Resolve(typeof(IInterface77));
            var resolvedInstance78 = container.Resolve(typeof(IInterface78));
            var resolvedInstance79 = container.Resolve(typeof(IInterface79));
            var resolvedInstance80 = container.Resolve(typeof(IInterface80));
            var resolvedInstance81 = container.Resolve(typeof(IInterface81));
            var resolvedInstance82 = container.Resolve(typeof(IInterface82));
            var resolvedInstance83 = container.Resolve(typeof(IInterface83));
            var resolvedInstance84 = container.Resolve(typeof(IInterface84));
            var resolvedInstance85 = container.Resolve(typeof(IInterface85));
            var resolvedInstance86 = container.Resolve(typeof(IInterface86));
            var resolvedInstance87 = container.Resolve(typeof(IInterface87));
            var resolvedInstance88 = container.Resolve(typeof(IInterface88));
            var resolvedInstance89 = container.Resolve(typeof(IInterface89));
            var resolvedInstance90 = container.Resolve(typeof(IInterface90));
            var resolvedInstance91 = container.Resolve(typeof(IInterface91));
            var resolvedInstance92 = container.Resolve(typeof(IInterface92));
            var resolvedInstance93 = container.Resolve(typeof(IInterface93));
            var resolvedInstance94 = container.Resolve(typeof(IInterface94));
            var resolvedInstance95 = container.Resolve(typeof(IInterface95));
            var resolvedInstance96 = container.Resolve(typeof(IInterface96));
            var resolvedInstance97 = container.Resolve(typeof(IInterface97));
            var resolvedInstance98 = container.Resolve(typeof(IInterface98));
            var resolvedInstance99 = container.Resolve(typeof(IInterface99));
            ;
#endregion
        }
    }
}