// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DpdtInject.Extension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string dpdtPackageString = "d53ea3df-798b-402f-b6fd-0dc4544a4be7";
        public static Guid dpdtPackage = new Guid(dpdtPackageString);

        public const string logo2_16_galleryString = "015c876b-a40e-42ed-a616-c95e83fbfc99";
        public static Guid logo2_16_gallery = new Guid(logo2_16_galleryString);

        public const string logo2_32_galleryString = "e8fe0869-dfed-4f46-be04-938805281cfa";
        public static Guid logo2_32_gallery = new Guid(logo2_32_galleryString);

        public const string guidDpdtPackageCmdSetString = "a30c3b4b-537c-4eef-a7ff-232d47063286";
        public static Guid guidDpdtPackageCmdSet = new Guid(guidDpdtPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int logo2_16 = 0x0001;
        public const int logo2_32 = 0x0001;
        public const int DpdtMenuGroup = 0x101D;
        public const int DpdtSubMenuGroup = 0x101E;
        public const int DpdtSubMenu = 0x101F;
        public const int DpdtInstallMenuGroup = 0x1020;
        public const int DoInstallCommandId = 0xC100;
        public const int DoCreateClusterMenuGroup = 0x1021;
        public const int DoCreateClusterCommandId = 0xC101;
        public const int BindingListWindowCommandId = 0xC102;
    }
}