name: dpdt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild
    - name: Test
      run: dotnet test DpdtInject.Tests\DpdtInject.Tests.csproj --no-build --verbosity normal
